# Site settings
title: Joe's Website
email: jjromano@albany.edu
description: Joe is a UAlbany Student from NY.
url: http://joeromano523.github.io
github_username: Joeromano523

# Build settings
markdown: kramdown
permalink: pretty
